#tomcat
server.port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:mem:fabrica
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
